 deploy:
    needs: build
    runs-on: contabo-prod-vm

    steps:
      - name: Pull image from Docker Hub
        run: sudo docker pull zrkhan/order-management:bridgertu

      - name: Delete old container
        run: sudo docker rm -f bridgertu-management-service-container-test || true

      - name: Run Docker container
        run: sudo docker run -d -p 8081:8081 --name bridgertu-management-service-container-test --restart always zrkhan/order-management:bridgertu
      - name: Docker Image Prune
        run: sudo docker image prune -f
