name: Test Pipeline

on:
  workflow_dispatch:
    
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login Dockerhub
      run: docker login -u zrkhan -p Lancher@1515
      
    - name: Build the Docker image
      run: docker build -t zrkhan/order-management:bridgertu .
    - name: Push to Dockerhub
      run: docker push zrkhan/order-management:bridgertu
